# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Erik Reinertsen
tagline:          "let's invent the future of medicine"
description:      'Thoughts on medicine, tech, and startup culture'
url:              http://erikreinertsen.github.io/
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
